#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".gcp-deploy.env"

require_value() {
  local value="$1" pattern="$2" label="$3"
  if [[ ! "$value" =~ $pattern ]]; then
    warn "$label 格式不正確。"
    exit 1
  fi
}

banner "Interview Coach · GCP Cloud Run setup"

stage "安裝必要工具"
say "需要 Google Cloud CLI、Terraform、GitHub CLI 與 Docker。"
missing=()
for tool in gcloud terraform gh docker; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if (( ${#missing[@]} )); then
  warn "缺少：${missing[*]}"
  open_url "https://cloud.google.com/sdk/docs/install"
  open_url "https://developer.hashicorp.com/terraform/install"
  open_url "https://cli.github.com/"
  open_url "https://docs.docker.com/engine/install/"
  say "安裝完成後重新執行這支精靈。"
  exit 1
fi
step "確認 Docker Desktop 或 Docker Engine 已啟動。"
docker info >/dev/null
note "API 啟用本身不收費；Cloud Run、Artifact Registry、儲存與網路依實際使用量計費。"
pause "工具已就緒，按 Enter 繼續。"

stage "登入 Google Cloud 與 GitHub"
say "登入流程會開啟官方瀏覽器頁面；專案不會保存服務帳號金鑰。"
if ! gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q .; then
  gcloud auth login
fi
step "建立 Terraform 使用的 Application Default Credentials。"
if ! gcloud auth application-default print-access-token >/dev/null 2>&1; then
  gcloud auth application-default login
fi
if ! gh auth status >/dev/null 2>&1; then
  gh auth login --web
fi

stage "選擇專案、帳務與 GitHub repository"
gcloud projects list --format='table(projectId,name)' || true
ask PROJECT_ID "GCP project id："
require_value "$PROJECT_ID" '^[a-z][a-z0-9-]{4,28}[a-z0-9]$' "GCP project id"
gcloud config set project "$PROJECT_ID" >/dev/null
step "將 Terraform ADC 的 quota project 設為所選專案。"
gcloud auth application-default set-quota-project "$PROJECT_ID"
open_url "https://console.cloud.google.com/billing/linkedaccount?project=${PROJECT_ID}"
step "確認這個專案已連結帳務帳戶，再從 Billing → Account management 複製 Billing account ID。"
ask BILLING_ACCOUNT_ID "Billing account ID（例如 000000-000000-000000）："
require_value "$BILLING_ACCOUNT_ID" '^[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}$' "Billing account ID"
ask NOTIFICATION_EMAIL "接收預算與服務告警的 email："
require_value "$NOTIFICATION_EMAIL" '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' "email"
detected_repo=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
ask GITHUB_OWNER "GitHub owner（目前偵測：${detected_repo%%/*}）："
ask GITHUB_REPOSITORY "GitHub repository 名稱（目前偵測：${detected_repo#*/}）："
[[ -z "$GITHUB_OWNER" && "$detected_repo" == */* ]] && GITHUB_OWNER="${detected_repo%%/*}"
[[ -z "$GITHUB_REPOSITORY" && "$detected_repo" == */* ]] && GITHUB_REPOSITORY="${detected_repo#*/}"
require_value "$GITHUB_OWNER" '^[A-Za-z0-9_.-]+$' "GitHub owner"
require_value "$GITHUB_REPOSITORY" '^[A-Za-z0-9_.-]+$' "GitHub repository"
ask STATE_BUCKET "Terraform state bucket（Enter 使用 ${PROJECT_ID}-interview-coach-tfstate）："
STATE_BUCKET="${STATE_BUCKET:-${PROJECT_ID}-interview-coach-tfstate}"
require_value "$STATE_BUCKET" '^[a-z0-9][a-z0-9._-]{1,61}[a-z0-9]$' "state bucket"
write_env PROJECT_ID "$PROJECT_ID"
write_env NOTIFICATION_EMAIL "$NOTIFICATION_EMAIL"
write_env GITHUB_OWNER "$GITHUB_OWNER"
write_env GITHUB_REPOSITORY "$GITHUB_REPOSITORY"
write_env STATE_BUCKET "$STATE_BUCKET"

stage "檢查並建立 GCP 基礎資源"
say "Terraform 將顯示完整 plan：必要 API、Artifact Registry、state bucket、WIF、服務帳號、email 通知與帳務幣別 1 單位的月預算。"
terraform -chdir=infra/bootstrap init -input=false
plan_file=$(mktemp "${TMPDIR:-/tmp}/interview-coach-bootstrap-plan.XXXXXX")
trap 'rm -f "$plan_file"' EXIT
terraform -chdir=infra/bootstrap plan -input=false -out="$plan_file" \
  -var="project_id=${PROJECT_ID}" \
  -var="github_owner=${GITHUB_OWNER}" \
  -var="github_repository=${GITHUB_REPOSITORY}" \
  -var="billing_account_id=${BILLING_ACCOUNT_ID}" \
  -var="notification_email=${NOTIFICATION_EMAIL}" \
  -var="state_bucket_name=${STATE_BUCKET}"
note "預算只發送通知，不會自動停止服務。Cloud Run 設為 min 0、max 1。"
if ! confirm "plan 看起來正確，要建立這些 GCP 資源嗎？"; then
  warn "尚未套用；之後重新執行即可。"
  exit 0
fi
terraform -chdir=infra/bootstrap apply -input=false "$plan_file"
rm -f "$plan_file"
trap - EXIT

stage "設定 GitHub Actions variables"
gh repo set-default "${GITHUB_OWNER}/${GITHUB_REPOSITORY}"
set_var GCP_PROJECT_ID "$PROJECT_ID"
set_var GCP_REGION "asia-east1"
set_var GCP_ARTIFACT_REPOSITORY "$(terraform -chdir=infra/bootstrap output -raw artifact_repository)"
set_var GCP_CLOUD_RUN_SERVICE "adaptive-english-interview-coach"
set_var GCP_TERRAFORM_STATE_BUCKET "$(terraform -chdir=infra/bootstrap output -raw terraform_state_bucket)"
set_var GCP_RUNTIME_SERVICE_ACCOUNT "$(terraform -chdir=infra/bootstrap output -raw runtime_service_account)"
set_var GCP_NOTIFICATION_CHANNEL "$(terraform -chdir=infra/bootstrap output -raw notification_channel)"
set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$(terraform -chdir=infra/bootstrap output -raw workload_identity_provider)"
set_var GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT "$(terraform -chdir=infra/bootstrap output -raw workload_identity_service_account)"
gh api --method PUT "repos/${GITHUB_OWNER}/${GITHUB_REPOSITORY}/environments/production" >/dev/null
note "GitHub 只保存非敏感識別值；部署時透過 OIDC 換取短效 GCP 憑證。"

stage "開啟 production 人工核准"
open_url "https://github.com/${GITHUB_OWNER}/${GITHUB_REPOSITORY}/settings/environments"
step "打開 production environment。"
step "在 Deployment protection rules 啟用 Required reviewers，加入你自己或指定 reviewer。"
step "只有一位維護者時，不要勾 Prevent self-review，否則你無法核准自己的首次部署。"
step "儲存 protection rules。"
pause "設定完成後按 Enter。"

stage "觸發首次部署並驗證"
say "部署 workflow 會重新跑測試、建置 SHA image、套用 Cloud Run/監控，最後檢查 /api/health。失敗時會把流量切回上一個 revision。"
if confirm "現在從 main 觸發首次 production deployment 嗎？"; then
  previous_run_id=$(gh run list --workflow deploy.yml --event workflow_dispatch --branch main --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)
  gh workflow run deploy.yml --ref main
  open_url "https://github.com/${GITHUB_OWNER}/${GITHUB_REPOSITORY}/actions/workflows/deploy.yml"
  step "在等待中的 deployment 按 Review deployments，核准 production。"
  pause "核准後按 Enter，精靈會等待結果。"
  run_id=""
  for attempt in $(seq 1 15); do
    run_id=$(gh run list --workflow deploy.yml --event workflow_dispatch --branch main --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)
    [[ -n "$run_id" && "$run_id" != "$previous_run_id" ]] && break
    sleep 2
  done
  [[ -n "$run_id" && "$run_id" != "$previous_run_id" ]] || { warn "找不到剛觸發的 workflow run；請到 Actions 頁面查看。"; exit 1; }
  gh run watch "$run_id" --exit-status
  service_url=$(gcloud run services describe adaptive-english-interview-coach --project "$PROJECT_ID" --region asia-east1 --format='value(status.url)')
  say "部署完成：${service_url}"
  open_url "$service_url"
else
  SKIPPED+=("首次部署（之後執行：gh workflow run deploy.yml --ref main）")
fi

finish
